FROM node:12-alpine
STOPSIGNAL SIGCONT

RUN set -x && \
    apk update && \
    apk upgrade && \
    apk add --update bash && \
    rm  -rf /tmp/* /var/cache/apk/* /opt/installer
RUN mkdir -p /usr/src/web-app/dist /usr/src/web-app/src
RUN addgroup -S www-data
RUN adduser -D -S -h /usr/src/web-app -s /sbin/nologin -G www-data www-data
