FROM tuiteraz/nginx-more:1.27.0-1.0.4

ARG IMAGE_VERSION
ARG IMAGE_NAME
ENV IMAGE_VERSION=$IMAGE_VERSION
ENV IMAGE_NAME=$IMAGE_NAME

COPY ./src/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

RUN rm -rf /etc/nginx
COPY ./src/nginx-config /etc/nginx

EXPOSE 80

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/usr/sbin/nginx"]