FROM node:22-bullseye-slim
STOPSIGNAL SIGCONT

RUN npm install -g npm@10.8.1
RUN apt-get update && apt-get install -y make
RUN addgroup --system node-js && \
  adduser --system --home /usr/src/app --ingroup node-js node-js
